const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const nodes=new Map(),toggles=[];
const node=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',addEventListener(){}});return nodes.get(s)};
const ctx=vm.createContext({document:{querySelector:node,body:{classList:{toggle(...args){toggles.push(args)}}}},window:{addEventListener(){}},fetch:()=>new Promise(()=>{}),location:{hash:""},console});
vm.runInContext(fs.readFileSync('web/app.js','utf8'),ctx);
vm.runInContext(`data={sector_id:'semiconductor',sector_name:'반도체',years:[2023,2024,2025],companies:[{code:'a',name:'A',history:[{year:2023,basis:'CFS',revenue:100,yoy:{}},{year:2024,basis:'CFS',revenue:110,yoy:{revenue:10}},{year:2025,basis:'CFS',revenue:99,yoy:{revenue:-10}}]},{code:'b',name:'B',history:[{year:2023,basis:'CFS',revenue:200,yoy:{}},{year:2024,basis:'CFS',revenue:240,yoy:{revenue:20}},{year:2025,basis:'CFS',revenue:288,yoy:{revenue:20}}]}],weighted_history:[],market:{representative_weights:{a:0.5,b:0.5},quotes:{}}};selectedYear=2025`,ctx);
const chart=vm.runInContext("trendLines('revenue',null)",ctx);
assert(chart.includes('zero-line'));
assert(chart.includes('data-series="a"'));
assert(chart.includes('data-series="b"'));
assert(chart.includes('data-chart-year="2025"'));
assert(chart.includes('data-chart-key="revenue"'));
assert(chart.includes('chart-legend'));
const metrics=vm.runInContext('keyMetrics(null)',ctx);
assert(metrics.includes('전년 대비 변동률'));
assert(!metrics.includes('metric-year'));
assert(!metrics.includes('class="spark"'));
assert.equal(vm.runInContext('trendScale([0,10,-10]).logarithmic',ctx),false);
assert.equal(vm.runInContext('trendScale([0,10000,-10000]).logarithmic',ctx),true);
assert(vm.runInContext('quoteCards()',ctx).includes('#company:semiconductor:a'));
vm.runInContext('nav(null);nav(data.companies[0])',ctx);
assert.deepEqual(toggles,[['company-view',false],['company-view',true]]);
console.log('Current UI tests passed: three-year trends, zero baseline, series/point references, company routes, log scale, no year selector.');
