const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const nodes=new Map();
const node=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',addEventListener(){}});return nodes.get(s)};
const ctx=vm.createContext({document:{querySelector:node,body:{classList:{toggle(){}}}},window:{addEventListener(){}},fetch:()=>new Promise(()=>{}),console});
vm.runInContext(fs.readFileSync('web/app.js','utf8'),ctx);
vm.runInContext(`data={years:[2024,2025],companies:[{code:'a',name:'A',history:[{year:2024,basis:'CFS',margin:1},{year:2025,basis:'CFS',margin:5}]},{code:'b',name:'B',history:[{year:2024,basis:'CFS',margin:2},{year:2025,basis:'CFS',margin:-3}]},{code:'c',name:'C',history:[{year:2025,basis:'CFS',margin:null}]}],weighted_history:[],market:{}};selectedYear=2025`,ctx);
assert.equal(vm.runInContext("changeLabel(data.companies[0].history,'margin')",ctx),'전년 대비 +4.0%p');
assert.equal(vm.runInContext("changeLabel([{year:2024,basis:'CFS',margin:1},{year:2025,basis:'OFS',margin:3}],'margin')",ctx),'재무 기준 변경 · 비교 제외');
assert.equal(vm.runInContext("changeLabel(data.companies[2].history,'margin')",ctx),'전년 비교 자료 없음');
let bars=vm.runInContext("comparisonBars('margin')",ctx);
assert(bars.indexOf('<small>B</small>')<bars.indexOf('<small>A</small>'));
assert(bars.indexOf('<small>A</small>')<bars.indexOf('<small>C</small>'));
vm.runInContext('nav(null)',ctx);assert.equal(node('#companies').innerHTML,'');
vm.runInContext('nav(data.companies[0])',ctx);assert(node('#companies').innerHTML.includes('#b'));
let metrics=vm.runInContext('keyMetrics(null)',ctx);assert(!metrics.includes('class="spark"'));assert(metrics.includes('metric-year'));
vm.runInContext('selectedYear=2024',ctx);bars=vm.runInContext("comparisonBars('margin')",ctx);assert(bars.indexOf('<small>A</small>')<bars.indexOf('<small>B</small>'));
console.log('UI tests passed: year selection, deltas, missing/basis changes, sorting, sidebar, removed sparklines');
